MaxEventSize: 0

Writable:
  LogLevel: INFO

Service:
  Host: localhost
  Port: 59997
  StartupMsg: device opcua started

MessageBus:
  Optional:
    ClientId: device-opcua

Device:
  DevicesDir: ./res/devices
  ProfilesDir: ./res/profiles
