# Pre-define Devices
[[DeviceList]]
  Name = "SimulationServer"
  ProfileName = "OPCUA-Server"
  Description = "OPCUA device is created for test purpose"
  Labels = [ "test" ]
  [DeviceList.Protocols]
      [DeviceList.Protocols.opcua]
          Endpoint = "opc.tcp://127.0.0.1:53530/OPCUA/SimulationServer"
          Policy = "None"                   # Security policy: None, Basic128Rsa15, Basic256, Basic256Sha256. Default: None
          Mode = "None"                     # Security mode: None, Sign, SignAndEncrypt. Default: None
          CertFile = ""                     # Path to cert.pem. Required for security mode/policy != None
          KeyFile = ""                      # Path to private key.pem. Required for security mode/policy != None
          Resources = "Counter,Random"