name: Go Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make docker

  test:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: test-artifacts/*.*
